version: 2
defaults: &defaults

jobs:
  test:
    docker:
      - image: circleci/golang:1.12.4
    working_directory: /go/src/github.com/kubesure/premium  
    steps:
      - checkout
      - run: go test -run TestMarshal  
  push:
    machine:
      image: circleci/classic:201808-01
      docker_layer_caching: true
    steps:
      - checkout
      - run: 
          name: build tag push
          command: |
            docker build -t $DOCKERHUB_USERNAME/premiumcalc:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/premiumcalc:$CIRCLE_SHA1
workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DockerHub
          filters:
            branches:
              only: master        
      - build:
          context: DockerHub 
          requires:
            - test
          filters:
            branches:
              only: master