version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.4

    working_directory: /go/src/github.com/kubesure/premium
    
    steps:
      - checkout

      #- run: go get -v -t -d ./...
      - run: go test -v ./...