version: 2
defaults: &defaults
  working_directory: /go/src/github.com/kubesure/premium
jobs:
  test:
    docker:
      - image: circleci/golang:1.12.4
    steps:
      - checkout
      - run: go test -run TestMarshal
  build:
    docker:
      - image: circleci/golang:1.12.4
    steps:
      - checkout
      - run: 
          name: build image
          command: |
            docker build . -t $DOCKERHUB_USERNAME/premiumcalc:$CIRCLE_SHA1
  push:
    docker:
      - image: circleci/golang:1.12.4
    steps:
      - checkout
      - run: 
          name: tag and push image
          command: |
            docker build -t $DOCKERHUB_USERNAME/premiumcalc:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
            docker push $DOCKERHUB_USERNAME/premiumcalc:$CIRCLE_SHA1	
workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DockerHub
          filters:
            branches:
              only: master        
      - build:
          context: DockerHub 
          requires:
            - test
          filters:
            branches:
              only: master
      - push:
          context: DockerHub
          requires:
            - build
          filters:
            branches:
              only: master     
