apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  labels:
    app: redis
    role: master
    tier: backend
data:
  master.conf: |- 
    bind 0.0.0.0
    port 6379
    save 900 1
    dir /redis-data
  slave.conf: |-
    bind 0.0.0.0
    port 6379
    dir .
    slaveof redis-premium-master-0.redissvc.default.svc.cluster.local 6379
  sentinel.conf: |- 
    bind 0.0.0.0
    port 26379
    sentinel monitor redis-premium-master redis-premium-master-0.redissvc.default.svc.cluster.local 6379 2
    sentinel parallel-syncs redis-premium-master 1
    sentinel down-after-milliseconds redis-premium-master 10000
    sentinel failover-timeout redis-premium-master 20000
  sentinel.sh: |- 
    #!/bin/bash
    cp /redis-config/sentinel.conf /sentinel.conf
    while ! ping -c 1 redis-premium-master-0.redissvc.default.svc.cluster.local; do
      echo 'Waiting for server'
      sleep 1
    done
    redis-sentinel /sentinel.conf
  init.sh: |-
    #!/bin/bash
    if [[ ${HOSTNAME} == 'redis-premium-master-0' ]]; then
      redis-server /redis-config/master.conf
    else
      redis-server /redis-config/slave.conf
    fi