kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-volume
  labels:
    app: premium
    type: DB
spec:
  storageClassName: manual
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/sfw
    server: 172.31.46.92
    readOnly: false
