apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-premium-master
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: 3
  serviceName: redissvc
  #selector:
    #matchLabels:
      #app: redis
      #role: master
      #tier: backend 
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - command: [sh, -c, source /redis-config/init.sh]
        image: redis:3.2.7-alpine
        name: redis
        ports: 
        - containerPort: 6379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config    
      - containers:
      - command: [sh, -c, source /redis-config/init.sh]
        image: redis:3.2.7-alpine
        name: sentinel
        ports: 
        - containerPort: 6379
        volumeMounts: 
        - mountPath: /redis-data
          name: data
        - mountPath: /redis-config
          name: config          
      volumes: 
      - configMap: 
          defaultMode: 420
          name: redis-config
        name: config
      - emptydir: 
          name: data              